version: "3"
services:
  perchfms-db:
    image: postgres:12-alpine
    container_name: perchfm-db
    expose:
      - "5400"
    ports:
      - "5400:5400"
    environment:
      POSTGRES_PASSWORD: password
      TZ: "UTC"
      PGTZ: "UTC"
    volumes:
      - ./schemas/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
    command: -p 5400
  perchfms-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perchfms-api
    image: perchfms-api:dev
    ports:
      - 8000:8000
    depends_on:
      - perchfms-db
    environment:
      HTTP_PORT: 8080
      HTTP_SHUTDOWN_TIMEOUT: 5000
      HTTP_CORS_ALLOW_ORIGINS: '["http://localhost:9000", "http://localhost:4200", "http://localhost:3000", "http://localhost:5000", "http://192.168.1.159:4200", "http://10.0.2.2:4200"]'
      ENVIRONMENT: local
    env_file:
      - api/.db.env
