version: "3"
services:
  messenger-db:
    image: postgres:12-alpine
    container_name: perchfm-db
    expose:
      - "5433"
    ports:
      - "5400:5400"
    environment:
      POSTGRES_PASSWORD: password
      TZ: "UTC"
      PGTZ: "UTC"
    volumes:
      - ./schema/Schemas.sql:/docker-entrypoint-initdb.d/Schemas.sql
    command: -p 5400
  messenger:
    image: messenger:dev
    container_name: messenger
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    depends_on:
      - messenger-db
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules
volumes:
  node_modules: